version: '3.3'
services:
    pidgin_sipe:
        volumes:
            - '/etc/localtime:/etc/localtime'
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            - '${HOME}/.pidgin:/home/.purple'
        environment:
            - DISPLAY=unix$DISPLAY
        links:
        logging:
            options:
                max-size: 1g
        devices:
            - /dev/snd
            - /dev/dri
            - /dev/video0
        image: silverbios/pidgin_sipe
